name: brooks_xpeel_module
services:
  brooks_xpeel_module:
    container_name: brooks_xpeel_module
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${IMAGE}:latest
        - ${IMAGE}:dev
    command: python -m brooks_xpeel_rest_node --port 2001 --device ${XPEEL_DEVICE}
    privileged: true
    env_file: .env
    volumes:
      - /dev:/dev
      - ./src:/home/app/brooks_xpeel_module/src
      - ./tests:/home/app/brooks_xpeel_module/tests
    ports:
      - 2001:2001
